### ISSUE TITLE
Wrong result and error when several same items in two sequences

### ISSUE THREAD

**Issue by AnticPan** [m-matelski/mdiff#12]
The package not works in some special cases and can raise TypeError.

**Wrong Output Case**
Good case:
```py
In [1]: HeckelSequenceMatcher([3,4], [3,5], replace_mode=True).get_opcodes()
Out[1]: [OpCode('equal', 0, 1, 0, 1), OpCode('replace', 1, 2, 1, 2)]
```
Bad case:
```py
In [1]: HeckelSequenceMatcher([3,3,4], [3,3,5], replace_mode=True).get_opcodes()
Out[1]: [OpCode('replace', 0, 3, 0, 3)]
```
should be [OpCode('equal', 0, 2, 0, 2), OpCode('replace', 2, 3, 2, 3)]

**TypeError Case**
Good case: ([2,1,3,4], [1,2,3,5])
Bad case: ([2,1,3,3,4], [1,2,3,3,5]) or ([2,1,3,...,3,4],[1,2,3,...,3,5])

```py
----> 1 HeckelSequenceMatcher([2,1,3,3,4], [1,2,3,3,5], replace_mode=True).get_opcodes()

File python3.8/site-packages/mdiff/seqmatch/heckel.py:275, in HeckelSequenceMatcher.get_opcodes(self)
    273 def get_opcodes(self) -> List[OpCode]:
    274     self.alg.run()
--> 275     opcodes = self.opcode_extractor.get_opcodes()
    276     return opcodes

File python3.8/site-packages/mdiff/seqmatch/heckel.py:209, in HeckelOpCodeExtractor.get_opcodes(self)
    206 prev_moved_val = None
    207 moved_i_index = self._oa(j)
    208 while (j < len(self.alg.oa) and self.__is_moved(j)) and (
--> 209         not prev_moved_val or self._oa(j) == prev_moved_val + 1):
    210     prev_moved_val = self._oa(j)
    211     j += 1

TypeError: unsupported operand type(s) for +: 'HeckelSymbolTableEntry' and 'int'
```

**Comment by m-matelski** [comment]
Regarding case:
> ```python
> In [1]: HeckelSequenceMatcher([3,3,4], [3,3,5], replace_mode=True).get_opcodes()
> Out[1]: [OpCode('replace', 0, 3, 0, 3)]
`HeckelSequenceMatcher` might sometimes generate not fully optimal result, it's how algorithm works. However sequences compared in example are quite simple, so I'll try to investigate it in future. For more strict sequences comparison `DisplacementSequenceMatcher` can be used. For now `get_opcodes()` raising TypeError exception has been fixed, as it is crucial for using this library.

Thanks for contributing!
